fullnameOverride: "pom"
prometheusOperator:
  admissionWebhooks:
    patch:
      nodeSelector:
        agentpool: default

prometheus:
  prometheusSpec:
    enableAdminAPI: true
    nodeSelector:
      agentpool: default
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: pv-prometheus-db
        spec:
          storageClassName: azure-disk-standard-ssd-lrs
          accessModes: ["ReadWriteOnce"]
          persistentVolumeReclaimPolicy: Retain
          resources:
            requests:
              storage: 30Gi
        selector: {}

grafana:
  service:
    type: LoadBalancer
    port: 443

kubeProxy:
  service:
    selector:
      component: kube-proxy
