parameters:
  azureSubscription:
  aksResourceGroupName:
  aksClusterName:
  additionalUpgradeAgs: ' '
  chartName:
  releaseName:
  valuesFile: ''
  namespace: default

steps:
- task: KubectlInstaller@0
  displayName: 'Install Kubectl latest'
- task: HelmInstaller@1
  displayName: 'Install Helm'
  inputs:
    helmVersionToInstall: latest
- task: HelmDeploy@0
  displayName: 'helm upgrade ${{parameters.additionalUpgradeAgs}}'
  inputs:
    azureSubscription: '${{parameters.azureSubscription}}'
    azureResourceGroup: '${{parameters.aksResourceGroupName}}'
    kubernetesCluster: '${{parameters.aksClusterName}}'
    useClusterAdmin: true
    command: upgrade
    namespace: '${{parameters.namespace}}'
    chartName: '${{parameters.chartName}}'
    releaseName: '${{parameters.releaseName}}'
    valueFile: '${{parameters.valuesFile}}'
    arguments: '${{parameters.additionalUpgradeAgs}}'
