parameters:
  AzureSubscription: ''
  IndexFile: ''
  CreateIndexScriptPath: '$(Build.SourcesDirectory)\PSScripts\Set-SearchIndexes.ps1'
  SearchName: ''
  SearchResourceGroupName: ''
  Location: 'West Europe'

steps:
- task: AzurePowerShell@5
  displayName: 'Create Search Indexes'
  condition: and(succeeded(), ne(variables.IndexFile, ''))
  inputs:
    AzureSubscription: '${{ parameters.AzureSubscription }}'
    scriptType: filePath
    ScriptPath: '${{ parameters.CreateIndexScriptPath }}'
    ScriptArguments: '-SearchName ${{ parameters.SearchName }} -ResourceGroupName ${{ parameters.SearchResourceGroupName }} -IndexFilePath "${{ parameters.IndexFile }}"'
    azurePowerShellVersion: LatestVersion
