parameters:
  AzureSubscription: ''
  IndexFile: ''
  CreateIndexScriptUrl: https://raw.githubusercontent.com/SkillsFundingAgency/dfc-devops/master/PSScripts/Set-SearchIndexes.ps1
  CreateIndexScriptPath: '$(System.DefaultWorkingDirectory)\Set-SearchIndexes.ps1'
  SearchName: ''
  SearchResourceGroupName: ''
  Location: 'West Europe'

steps:
- task: PowerShell@2
  name: DownloadCreateIndexScript
  displayName: 'Download Index Creation script'
  inputs:
    targetType: 'inline'
    script: Invoke-WebRequest -Uri ${{ parameters.CreateIndexScriptUrl }} -OutFile ${{ parameters.CreateIndexScriptPath }}

- task: AzurePowerShell@3
  displayName: 'Create Search Indexes'
  condition: and(succeeded(), ne(variables.IndexFile, ''))
  inputs:
    AzureSubscription: '${{ parameters.AzureSubscription }}'
    scriptType: filePath
    ScriptPath: '${{ parameters.CreateIndexScriptPath }}'
    ScriptArguments: '-SearchName ${{ parameters.SearchName }} -ResourceGroupName ${{ parameters.SearchResourceGroupName }} -IndexFilePath "${{ parameters.IndexFile }}"'
    azurePowerShellVersion: LatestVersion
