parameters:
  AzureSubscription: ''
  IndexFile: ''
  ScriptPath: '$(Agent.BuildDirectory)/s/dfc-devops/PSScripts/Set-SearchIndexes.ps1'
  SearchName: ''
  SearchResourceGroupName: ''
  Location: 'West Europe'

steps:
- task: AzurePowerShell@3
  displayName: 'Create Search Indexes'
  condition: and(succeeded(), ne(variables.IndexFile, ''))
  inputs:
    AzureSubscription: '${{ parameters.AzureSubscription }}'
    ScriptPath: '${{ parameters.ScriptPath }}'
    ScriptArguments: '-SearchName ${{ parameters.SearchName }} -ResourceGroupName ${{ parameters.SearchResourceGroupName }} -IndexFilePath "${{ parameters.IndexFile }}"'
    azurePowerShellVersion: LatestVersion
