parameters:
  AksResourceGroup: ''
  AzureSubscriptionEndpoint: ''
  KubernetesCluster: ''
  Namespace: 'default'

steps:
#Create Namespace
- task: Kubernetes@1
  displayName: 'Create ${{ parameters.Namespace }} Namespace' 
  inputs:
    connectionType: Azure Resource Manager
    azureSubscriptionEndpoint: ${{ parameters.AzureSubscriptionEndpoint }}
    azureResourceGroup: ${{ parameters.AksResourceGroup }}
    kubernetesCluster: ${{ parameters.KubernetesCluster }}
    useClusterAdmin: true
    command: apply
    useConfigurationFile: true
    inline: '{ "kind": "Namespace", "apiVersion": "v1", "metadata": { "name": "${{ parameters.Namespace }}" }}'