variables:
- name: SolutionBaseName
  value: Dfc.DevOps

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    endpoint: 'GitHub (ESFA)'
    ref: refs/tags/v1.11.2

pool:
  name: 'NCS - CI and CD'
  demands:
    - PowerShell
    - AzurePS
    - docker

trigger:
  branches:
    include:
    - master
    - dev

pr:
  branches:
    include:
    - master
    - dev


stages:
- template: StageTemplates/RunTests.yml
  parameters:
    AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
    Powershell5CodeCoveragePercentage: 45
    PowershellCoreCodeCoveragePercentage: 25

