variables:
- name: SolutionBaseName
  value: Dfc.DevOps
- name: ServiceOffering
  value: 'Digital First Career Service (DFCS) Website'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    endpoint: 'GitHub (ESFA)'
    ##TO DO: revert to tag
    ref: refs/heads/NCSD-3023-AddPrometheusK8sDeploymemt

pool:
  name: 'NCS - CI and CD'
  demands:
    - PowerShell
    - AzurePS
    - docker

trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master


stages:
- template: StageTemplates/RunTests.yml
  parameters:
    AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
    Powershell5CodeCoveragePercentage: 45
    PowershellCoreCodeCoveragePercentage: 25

- stage: BuildResources
  dependsOn: []
  jobs:
  - job: TestAndPublishArmTemplates
    displayName: Test and Publish Arm Templates
    steps:
    - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml@dfc-devops
      parameters:
        ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates'
        SolutionBaseName: ${{ variables.SolutionBaseName }}
        PublishPipelineArtifact: true

- stage: BuildAndPublishContainers
  condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.Reason'], 'PullRequest'))
  dependsOn: []
  variables:
  - group: KeyVault - dfc-dev-shared-kv
  - group: dfc-shared-dev
  jobs:
  - template: JobTemplates\BuildAndPublishLinuxContainers.yml
    parameters:
      ContainerRegistryAdminUser: $(ContainerRegistryAdminUser)
      ContainerRegistryPassword: $(ContainerRegistryPassword)

- stage: DeployAzureDevOpsContainers
  condition: and(succeeded('BuildAndPublishContainers'), eq(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.Reason'], 'PullRequest'))
  dependsOn: BuildAndPublishContainers
  variables:
  - template: VariableTemplates\SharedEnvironmentVariables.yml
  - template: VariableTemplates\DevEnvironmentVariables.yml
  - group: KeyVault - dfc-dev-shared-kv
  - group: dfc-shared-dev
  jobs:
  - template: JobTemplates\DeployAzureDevOpsContainers.yml
    parameters:
      AksResourceGroup: $(sharedResourceGroup)
      AzurePatToken: $(AzureDevOpsAgentPatToken)
      AzureSubscriptionEndpoint: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      Environment: DEV_SHARED
      KubernetesCluster: $(sharedAksCluster)

- stage: DeployMonitoringToolsToDev
  ##TO DO: reinstate condition
  #condition: and(eq(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.Reason'], 'PullRequest'))
  dependsOn: []
  variables:
  - group: dfc-shared-all
  - group: dfc-shared-dev
  jobs:
  - template: JobTemplates\DeployPrometheus.yml
    parameters:
      AksResourceGroup: $(sharedResourceGroup)
      AzureSubscriptionEndpoint: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      Environment: DEV_SHARED
      EnvironmentTag: $(EnvironmentTag)
      KubernetesCluster: $(sharedAksCluster)
      ParentBusinessTag: $(ParentBusiness)
      ResourceGroup: $(AksNodeResourceGroupName)
      ServiceOfferingTag: ${{ variables.ServiceOffering }}
      