parameters:
  AzureSubscription: ''
  CodeCoveragePercentage: 80

stages:
- stage: Test
  jobs:
    - job: RunUnitTests
      displayName: "Run unit and acceptance tests"
      steps:
      - task: AzurePowerShell@3
        displayName: 'Azure PowerShell Script: Invoke-Tests'
        continueOnError: true
        inputs:
          azureSubscription: '${{ parameters.AzureSubscription }}'
          ScriptPath: '$(System.DefaultWorkingDirectory)/Tests/Invoke-Tests.ps1'
          ScriptArguments: '-ExcludeTag Quality -CodeCoveragePath $(System.DefaultWorkingDirectory)\PSScripts\*.ps1'
          azurePowerShellVersion: LatestVersion

      - task: PublishTestResults@2
        displayName: 'Publish Test Results'
        inputs:
          testResultsFormat: NUnit

      - task: PublishCodeCoverageResults@1
        displayName: 'Publish Code Coverage'
        inputs:
          summaryFileLocation: '**/CODECOVERAGE-*.xml'

      - task: PowerShell@2
        displayName: 'PowerShell Script: Out-TestResults'
        inputs:
          targetType: filePath
          filePath: '$(System.DefaultWorkingDirectory)/Tests/Out-TestResults.ps1'
          arguments: '-CoveragePercent ${{ parameters.CodeCoveragePercentage }}'

    - job: RunQualityTests
      displayName: "Run code quality tests"
      steps:
      - job: 'RunQualityTests'
        displayName: 'Run ${{ parameters.TestType }} tests'
        steps:
        - task: AzurePowerShell@3
          displayName: 'Azure PowerShell Script: Invoke-Tests'
          continueOnError: true
          inputs:
            azureSubscription: '${{ parameters.AzureSubscription }}'
            ScriptPath: '$(System.DefaultWorkingDirectory)/Tests/Invoke-Tests.ps1'
            ScriptArguments: '-ExcludeTag Quality -CodeCoveragePath $(System.DefaultWorkingDirectory)\PSScripts\*.ps1'
            azurePowerShellVersion: LatestVersion

        - task: PublishTestResults@2
          displayName: 'Publish Test Results'
          inputs:
            testResultsFormat: NUnit