parameters:
  AzureSubscription: ''
  CodeCoveragePercentage: 45

stages:
- stage: Test
  jobs:
  - template: ../JobTemplates/ExecuteTestType.yml
    parameters:
      TestType: Unit
  - template: ../JobTemplates/ExecuteTestType.yml
    parameters:
      TestType: Acceptance
  - template: ../JobTemplates/ExecuteTestType.yml
    parameters:
      TestType: Quality

  - job: PublishTestResults
    displayName: 'Publish test and code coverage results'
    dependsOn:
    - RunUnitTests
    - RunAcceptanceTests
    - RunQualityTests

    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        source: 'current'