parameters:
  AzureSubscription: ''
  CodeCoveragePercentage: 75

stages:
- stage: Test
  jobs:
    - template: ../JobTemplates/RunIndividualTest.yml
      parameters:
        AzureSubscription: '${{ parameters.AzureSubscription }}'
        TestName: 'RunAcceptanceTests'
        TestType: 'ArmAcceptance'
        ResultsFileSuffix: 'Acceptance'

    - template: ../JobTemplates/RunIndividualTest.yml
      parameters:
        AzureSubscription: '${{ parameters.AzureSubscription }}'
        TestName: 'RunQualityTests'
        TestType: 'Quality'
        ResultsFileSuffix: 'Quality'

    - template: ../JobTemplates/RunIndividualTest.yml
      parameters:
        AzureSubscription: '${{ parameters.AzureSubscription }}'
        TestName: 'RunScriptUnitTests'
        TestType: 'Unit'
        CodeCoveragePercentage: ${{ parameters.CodeCoveragePercentage }}
