parameters:
  AzureSubscription: ''
  Powershell5CodeCoveragePercentage: 80
  PowershellCoreCodeCoveragePercentage: 80

stages:
- stage: Test
  jobs:
    - template: ../JobTemplates/RunInvididualTest.yml
      parameters:
        UseAzurePowershell:  true
        AzureSubscription: '${{ parameters.AzureSubscription }}'
        TestType: 'Acceptance'

    - template: ../JobTemplates/RunInvididualTest.yml
      parameters:
        UseAzurePowershell:  false
        UsePowershellCore: true
        TestType: 'Quality'

    - template: ../JobTemplates/RunInvididualTest.yml
      parameters:
        UseAzurePowershell:  true
        AzureSubscription: '${{ parameters.AzureSubscription }}'
        TestType: 'Unit'
        CodeCoveragePercentage: ${{ parameters.Powershell5CodeCoveragePercentage }}

    - template: ../JobTemplates/RunInvididualTest.yml
      parameters:
        UseAzurePowershell:  false
        UsePowershellCore: true
        TestType: 'Unit'
        CodeCoveragePercentage: ${{ parameters.PowershellCoreCodeCoveragePercentage }}