parameters:
  ContainerRegistryAdminUser: ''
  ContainerRegistryPassword: ''

jobs:
- job: BuildAndPublishContainers
  pool:
    name: 'Hosted Ubuntu 1604'
  steps:
  # Build and publish the NCS.AzureDevOpsAgents.OWASP docker image
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-docker-publish-k8smanifest.yml@dfc-devops
    parameters:
      ContainerRegistryAdminUser: ${{ parameters.ContainerRegistryAdminUser }}
      ContainerRegistryPassword: ${{ parameters.ContainerRegistryPassword }}
      DockerfileContext: ./DockerFiles/AzureDevOpsAgents
      DockerfileName: owasp-agent.Dockerfile
      ImageBaseName: NCS.AzureDevOpsAgents.OWASP
      ImageTag: $(Build.BuildNumber)
      ManifestFilePath: 'DockerFiles/AzureDevOpsAgents/owasp-agent.kubernetes.yml'