parameters:
  AksResourceGroup:
  AzureSubscriptionEndpoint:
  Environment:
  GrafanaPublicIpAddress:
  GrafanaPublicIpAddressResourceGroup:
  KubernetesCluster:

jobs:
- job: ValidatePrometheus
  steps:
  - template: AzureDevOpsTemplates/Deploy/StepTemplates/dfc-helm-upgrade.yml@dfc-devops
    parameters:
      azureSubscription: ${{ parameters.AzureSubscriptionEndpoint }}
      aksResourceGroupName: ${{ parameters.AksResourceGroup }}
      aksClusterName: ${{ parameters.KubernetesCluster }}
      additionalUpgradeAgs: '--dry-run --set prometheusOperator.createCustomResource=false'
      chartName: stable/prometheus-operator
      releaseName: monitoring
      valuesFile: DockerFiles/Prometheus/prometheus-operator-values.yml
      continueOnError: true
      namespace: default
  - task: PublishPipelineArtifact@1
    displayName: 'Publish Pipeline Artifacts'
    inputs:
      path: ${{ parameters.appRoot }}
      artifactName: 'Dfc.DevOps.Prometheus'
- deployment: DeployPrometheus
  ##TO DO: decide where to place condition and reinstate
  #condition: and(succeeded('validate'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  environment: ${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - template: AzureDevOpsTemplates/Deploy/StepTemplates/dfc-helm-upgrade.yml@dfc-devops
          parameters:
            azureSubscription: ${{ parameters.AzureSubscriptionEndpoint }}
            aksResourceGroupName: ${{ parameters.AksResourceGroup }}
            aksClusterName: ${{ parameters.KubernetesCluster }}
            additionalUpgradeAgs: '--set prometheusOperator.createCustomResource=false --set grafana.service.annotations=service.beta.kubernetes.io/neo4j-escodb-resource-group:${{ parameters.GrafanaPublicIpAddressResourceGroup }} --set grafana.service.loadBalancerIP=${{ parameters.GrafanaPublicIpAddress }}'
            chartName: stable/prometheus-operator
            releaseName: monitoring
            valuesFile: $(Pipeline.Workspace)/Dfc.DevOps.Prometheus/prometheus-operator-values.yml
            namespace: default