parameters:
  AzureSubscription: ''
  TestName: ''
  TestType: ''  # One of 'Acceptance', 'Quality', "Unit"
  CodeCoveragePercentage: 80

jobs:
- job: ${{ parameters.TestName }}
  displayName: 'Run ${{ parameters.TestType }} tests'
  steps:
  - task: DeleteFiles@1
    displayName: 'Remove old test and code coverage files'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/Tests'
      Contents: |
        **/TEST-*.xml
        **/CODECOVERAGE-*.xml

  - task: AzurePowerShell@5
    displayName: 'AzurePowershell: Invoke-${{ parameters.TestType }}Tests.ps1'
    inputs:
      azureSubscription: '${{ parameters.AzureSubscription }}'
      ScriptPath: '$(System.DefaultWorkingDirectory)/Tests/Invoke-${{ parameters.TestType }}Tests.ps1'
      azurePowerShellVersion: 6.6.0
      pwsh: true

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    condition: always()
    inputs:
      testResultsFormat: NUnit
      testResultsFiles: '**/TEST-*.xml'
      mergeTestResults: true
      testRunTitle: 'Test Results'

  - ${{ if eq(parameters.TestType, 'Unit') }}:
    - task: PublishCodeCoverageResults@1
      displayName: 'Publish Code Coverage'
      inputs:
        summaryFileLocation: '**/CODECOVERAGE-*.xml'

    - task: PowerShell@2
      displayName: 'PowerShell Script: Out-TestResults'
      inputs:
        targetType: filePath
        filePath: '$(System.DefaultWorkingDirectory)/Tests/Out-TestAndCodeCoverageResults.ps1'
        arguments: '-CoveragePercent ${{ parameters.CodeCoveragePercentage }}'
        pwsh: true